/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:830991b4-bb09-46fa-b4b6-27b7c62f686b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GEgJ7PP3D",
    "aws_user_pools_web_client_id": "7umcb1nm1rj7svo0nh333ngdj0",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://nnaprrba2bg25mtndcftw776rq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dki3wawuwjhlnjmua637do4jle",
    "aws_user_files_s3_bucket": "authcra8935d87309ef41229e11d8cc074b1d79100421-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
